package com.tms.businessservice.service.impl;

import java.util.List;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.tms.businessservice.dto.request.ClientRequest;
import com.tms.businessservice.dto.response.ClientResponse;
import com.tms.businessservice.entity.Client;
import com.tms.businessservice.exception.ResourceNotFoundException;
import com.tms.businessservice.repository.ClientRepository;
import com.tms.businessservice.service.ClientService;

/**
 * Implements Client business rules and converts between DTOs and the Client
 * database entity.
 */
@Service
public class ClientServiceImpl implements ClientService {

    private final ClientRepository clientRepository;

    // Constructor injection makes the required repository dependency explicit.
    public ClientServiceImpl(ClientRepository clientRepository) {
        this.clientRepository = clientRepository;
    }

    @Override
    @Transactional
    public ClientResponse createClient(ClientRequest request) {

        // The ID and creation timestamp are generated by the database/Hibernate.
        Client client = Client.builder()
                .clientName(request.getClientName())
                .companyName(request.getCompanyName())
                .email(request.getEmail())
                .contact(request.getContact())
                .address(request.getAddress())
                .build();

        Client savedClient = clientRepository.save(client);
        return toResponse(savedClient);
    }

    @Override
    @Transactional(readOnly = true)
    public List<ClientResponse> getAllClients() {

        return clientRepository.findAll()
                .stream()
                .map(this::toResponse)
                .toList();
    }

    @Override
    @Transactional(readOnly = true)
    public ClientResponse getClientById(Integer clientId) {

        return toResponse(findClientOrThrow(clientId));
    }

    @Override
    @Transactional
    public ClientResponse updateClient(
            Integer clientId,
            ClientRequest request) {

        Client client = findClientOrThrow(clientId);

        client.setClientName(request.getClientName());
        client.setCompanyName(request.getCompanyName());
        client.setEmail(request.getEmail());
        client.setContact(request.getContact());
        client.setAddress(request.getAddress());

        Client updatedClient = clientRepository.save(client);
        return toResponse(updatedClient);
    }

    @Override
    @Transactional
    public void deleteClient(Integer clientId) {

        // Finding first allows the API to return a clear 404 later instead of
        // silently succeeding when the requested Client does not exist.
        Client client = findClientOrThrow(clientId);
        clientRepository.delete(client);
    }

    /**
     * Loads one Client or throws a reusable exception when the ID is invalid.
     */
    private Client findClientOrThrow(Integer clientId) {

        return clientRepository.findById(clientId)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "Client not found with ID: " + clientId));
    }

    /**
     * Converts the internal database entity into data safe for an API response.
     */
    private ClientResponse toResponse(Client client) {

        return ClientResponse.builder()
                .clientId(client.getClientId())
                .clientName(client.getClientName())
                .companyName(client.getCompanyName())
                .email(client.getEmail())
                .contact(client.getContact())
                .address(client.getAddress())
                .createdAt(client.getCreatedAt())
                .build();
    }
}
